# Generated by Django 3.2.8 on 2021-11-26 21:58

import classroom.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('score', models.IntegerField(blank=True, default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=classroom.models.image_path)),
                ('title', models.CharField(max_length=255)),
                ('attribute', models.CharField(max_length=255)),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('classroombasic_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroombasic')),
                ('user_pk', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(blank=True, null=True)),
                ('state', models.IntegerField(default=0)),
                ('season', models.IntegerField(default=1)),
                ('fee_submission', models.BooleanField(default=False)),
                ('date_join', models.DateTimeField(blank=True, null=True)),
                ('date_leave', models.DateTimeField(blank=True, null=True)),
                ('classroombasic_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroombasic')),
                ('user_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoomScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('classroombasic_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroombasic')),
                ('evaluator_pk', models.ForeignKey(on_delete=models.SET('deleted_user'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('grace_period', models.PositiveSmallIntegerField(blank=True, default=14)),
                ('max_user_count', models.IntegerField(blank=True, default=5)),
                ('user_count', models.IntegerField(blank=True, default=1)),
                ('main_goal', models.TextField()),
                ('season', models.IntegerField(blank=True, default=1)),
                ('date_renew', models.DateTimeField(auto_now_add=True)),
                ('period_renew', models.IntegerField(blank=True, default=30, validators=[django.core.validators.MinValueValidator(14)])),
                ('enterence_fee', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_money', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('meeting_days', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_times', models.CharField(blank=True, max_length=255, null=True)),
                ('penalty', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('classroombasic_pk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroombasic')),
            ],
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('classroombasic_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroombasic')),
                ('user_pk', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('attendance', models.BooleanField(blank=True, default=False)),
                ('classroombasic_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroombasic')),
                ('event', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='agora.studyevent')),
                ('group_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.group')),
            ],
        ),
    ]
